### ISSUE TITLE
Problem during initialization in loading data

### ISSUE THREAD

**Issue by azuki-miho** [XLechter/Detail-Preserved-Point-Cloud-Completion-via-SFA#3]
Traceback (most recent call last):
  File "eval.py", line 109, in <module>
    train(args)
  File "eval.py", line 33, in train
    provider = TrainProvider(args, is_training_pl)
  File "eval.py", line 17, in __init__
    args.num_input_points, args.num_gt_points, is_training=False)
  File "/all-data/linus-disk1/gongjingyu_home/gcode/others/Detail-Preserved-Point-Cloud-Completion-via-SFA/data_util.py", line 34, in lmdb_dataflow
    df = dataflow.LMDBSerializer.load(lmdb_path, shuffle=False)
  File "/all-data/linus-disk1/gongjingyu_home/.virtualenvs/SFA/lib/python3.6/site-packages/tensorpack/dataflow/serialize.py", line 114, in load
    df = LMDBData(path, shuffle=shuffle)
  File "/all-data/linus-disk1/gongjingyu_home/.virtualenvs/SFA/lib/python3.6/site-packages/tensorpack/dataflow/format.py", line 90, in __init__
    self._set_keys(keys)
  File "/all-data/linus-disk1/gongjingyu_home/.virtualenvs/SFA/lib/python3.6/site-packages/tensorpack/dataflow/format.py", line 110, in _set_keys
    self.keys = loads(self.keys)
  File "/all-data/linus-disk1/gongjingyu_home/.virtualenvs/SFA/lib/python3.6/site-packages/tensorpack/utils/serialize.py", line 93, in loads
    return pickle.loads(buf)
_pickle.UnpicklingError: invalid load key, '\xdc'.

I think the question maybe because of the lmdb data or the version of tensorpack, can you give some suggestions?

**Comment by XLechter** [comment]
Hi, @azuki-miho .
The most possible reason is the .lmdb file is incomplete when you download or transfer it to another mechine. You can try re-downloading the .lmdb file. 
Another possible reason may be the incompatible version between tensorpack and pickle.
Hope this helps : )

**Comment by azuki-miho** [comment]
So, I want to know your version of tensorpack

**Comment by XLechter** [comment]
@azuki-miho The tensorpack version is 0.9.0.1
